keywords = {
    "celé_číslo": "int",
    "desetinné_číslo": "float",
    "dlouhé_číslo": "long",
    "konstanta": "const",
    "dvojitý": "double",
    "znak": "char",
    "prázdno": "void",
    "tiskni": "printf",
    "hlavní": "main",
    "#zahrň": "#include",
    "struktura": "struct",
    "vykonávej": "do",
    "dokud": "while",
    "pro": "for",
    "pokud": "if",
    "jinak": "else",
    "vrať": "return",
    "statický|statické": "static",
    "přepínač": "switch",
    "případ": "case",
    "přiřaď": "=",
    "rovno": "==",
    "plus": "+",
    "minus": "-",
    "krát": "*",
    "děleno": "/",
    }
