#define celé_číslo int
#define desetinné_číslo float
#define dlouhé_číslo long
#define konstanta const
#define dvojitý double
#define znak char
#define prázdno void
#define tiskni printf
#define hlavní main
#define struktura struct
#define vykonávej do
#define dokud while
#define pro for
#define pokud if
#define jinak else
#define vrať return
#define statický static
#define statické static
#define přepínač switch
#define případ case
#define přiřaď =
#define rovno ==
#define plus +
#define minus -
#define krát *
#define děleno /
